### ISSUE TITLE
Places not displayed

### ISSUE THREAD

**Issue by gfranzini** [acdh-oeaw/dig_ed_cat#36] opened 2017-03-13 13:21 UTC
Some of the locations in the app are not displayed. The recent Tarsian project, for instance, contains one set of coordinates for the Swiss Institute of Bioinformatics but the app doesn't display the location in the map.
Is there anything I can do here to help?

**Comment by csae8092** [comment] 2017-03-15 09:41
The problem with the **Swiss Institute of Bio...** is caused by using different names. In [digEds_cat.csv](https://github.com/gfranzini/digEds_cat/blob/master/digEds_cat.csv) the string `Vital-IT Swiss Institute of Bioinformatics` is used, whereas in [digEds_cat_spatial.csv](https://github.com/gfranzini/digEds_cat/blob/master/digEds_cat_spatial.csv) the institution is called `SIB Swiss Institute of Bioinformatics`. Therefore the script to update the editions couldn't link to the 'right' institution. 
Besides this the way institutions are synced from github to the application as well as connected to the editions is not quite elegant yet.
1. The import script can only be triggered by me.
2. The script is written very poorly e.g it deletes all objects and created new ones instead of updating
3. It calls for each institution the geoname-api
4. ....

Therefore we should think about a slightly better solution... . First by improving the script (which is my part), but second, also by rethinking the way institutions are currently recorded in [digEds_cat_spatial.csv](https://github.com/gfranzini/digEds_cat/blob/master/digEds_cat_spatial.csv). For the latter I'd suggest to start from the institutions we have in the application and which can be exported as .csv from https://dig-ed-cat.acdh.oeaw.ac.at/editions/institution-csv/

**Comment by gfranzini** [comment] 2017-03-16 10:20
Ah, my mistake! I changed the Swiss entry in digEds_cat.csv to match the name in the .csv file. So that's one problem solved.
As for the "rethinking". Yes, this needs a more efficient solution. What does the 'Places' menu tab do in the app (when I'm logged in)? I see it lists cities. Is there a way I could enter the institution information in there directly?

**Comment by csae8092** [comment] 2017-04-12 15:08
Basically the whole application is a CRUD app, so you can/could create, edit any data directly in the app. But I think the way doing the curation/creation via GitHub works quite well (and I don't have to invest any time into fancy forms for editing and to set up some user management/registration system), so I'd say we stick with it. And by using the new institutions/places .csv the import/sync will get a lot easier. I will work on the sync script which will include institutions/places ([https://github.com/acdh-oeaw/dig_ed_cat/issues/40](https://github.com/acdh-oeaw/dig_ed_cat/issues/40)) and therefore close this issue

**Closed by csae8092** 2017-04-12 15:08 UTC

**Comment by gfranzini** [comment] 2017-04-12 16:17
Makes sense! The simpler the better.
